/**
 * ai.ts — Tweet generation via Cloudflare AI Gateway → Anthropic
 *
 * Design principles:
 *  1. SYSTEM PROMPT  — permanent identity: informal, creative, no title drops
 *  2. USER PROMPT    — dynamic context: post content, tweet history, today's theme
 *  3. ARC AWARENESS  — 10-tweet journey; each tweet nudges toward reading the post
 *  4. SIGNATURE TAG  — #هوشنوشت is always appended in code, never left to Claude
 *  5. LENGTH SAFETY  — fitToTwitterLimit trims gracefully, never crashes
 */

import { CLAUDE_MODEL, TWEET_THEMES } from "./config";
import type { Env, TweetGenerationInput, TweetGenerationResult } from "./types";

// ── AI signature hashtag (always appended, not generated by Claude) ───────────
const AI_SIGNATURE = "#هوشنوشت";

// ── System prompt ─────────────────────────────────────────────────────────────
const SYSTEM_PROMPT = `تو یه نویسنده خلاق و صمیمی هستی که برای اکانت توییتر «۲۵ مرداد» توییت می‌نویسی.

هدفت اینه که هر روز یه توییت بنویسی که آدم‌ها رو تشویق کنه مطلب رو بخونن — ولی نه با تبلیغ مستقیم. با یه ایده جذاب، یه سوال، یه جمله که توی ذهن می‌مونه.

قوانین ثابت:
- لحن: غیررسمی، دوستانه، خلاق — مثل یه آدم باهوش که با دوستش حرف می‌زنه
- زبان: فارسی محاوره‌ای روان — نه ادبی، نه خشک، نه خبری
- هرگز عنوان مطلب رو نگو — ایده‌ها رو مستقیم بیان کن
- هرگز بگو «در مطلب جدید» یا «در این پست» — انگار خودت داری فکر می‌کنی
- طول متن اصلی (بدون هشتگ): حداکثر ۱۹۰ کاراکتر
- هشتگ: ۱ تا ۲ هشتگ فارسی کوتاه و مرتبط — در یه خط جداگانه بعد از متن اصلی
- هرگز لینک اضافه نکن
- توییت باید با یه جمله کامل تموم بشه — هرگز با «...» یا «…» ختم نشه
- خروجی: فقط متن توییت — بدون توضیح، بدون پیشگفتار`;

// ── Build the user prompt dynamically each day ────────────────────────────────
function buildUserPrompt(input: TweetGenerationInput): string {
  const theme = TWEET_THEMES[input.themeIndex % TWEET_THEMES.length];
  const totalTweets = TWEET_THEMES.length; // 10
  const tweetsLeft = totalTweets - (input.themeIndex % totalTweets) - 1;

  // Section 1: post content
  const postSection = `
## محتوای مطلب
آدرس: ${input.post.url}

متن کامل:
---
${input.post.content}
---`.trim();

  // Section 2: tweet history (prevent repetition, show arc progress)
  const historySection =
    input.previousTweets.length === 0
      ? `## توییت‌های قبلی
هنوز هیچ توییتی ارسال نشده — این اولین توییت از این مطلبه.`
      : `## توییت‌های قبلی (${input.previousTweets.length} از ${totalTweets})
این‌ها رو قبلاً گفتیم — تکرار ممنوع:

${input.previousTweets
  .map((t, i) => `[${i + 1}] تم: ${t.theme}\n${t.tweet_text}`)
  .join("\n\n")}`;

  // Section 3: today's creative brief with arc context
  const arcContext =
    tweetsLeft === 0
      ? `این آخرین توییت از این مطلبه (${totalTweets} از ${totalTweets}) — جمع‌بندی کن و مخاطب رو به خوندن مطلب دعوت کن.`
      : tweetsLeft <= 2
      ? `${totalTweets - tweetsLeft} توییت از ${totalTweets} گفتیم — داریم به آخر نزدیک می‌شیم. کم‌کم به سمت دعوت به خوندن برو.`
      : `توییت ${input.previousTweets.length + 1} از ${totalTweets} — هنوز اول راهیم، خلاق باش و کنجکاوی ایجاد کن.`;

  const themeSection = `
## وظیفه امروز — تم: ${theme.label}
${theme.direction}

${arcContext}

توییت فارسی بنویس که:
- با زاویه «${theme.label}» نوشته شده باشه
- هیچ‌کدام از توییت‌های قبلی رو تکرار نکنه
- عنوان مطلب رو مستقیم نگه نداشته باشه
- حس بده یه آدم واقعی داره این رو می‌گه، نه یه ربات خبری
- متن اصلی (بدون هشتگ) حداکثر ۱۹۰ کاراکتر
- هشتگ‌ها در یه خط جداگانه بعد از متن بنویس، مثلاً:\n  متن متن متن\n  #ایران #تاریخ

فقط متن توییت رو بنویس:`.trim();

  return [postSection, historySection, themeSection].join("\n\n");
}

// ── Tweet length fitter ───────────────────────────────────────────────────────

/**
 * Fits a tweet within maxLen chars without crashing.
 * Strategy: drop topic hashtags one-by-one from the right, then trim body.
 * NOTE: the AI_SIGNATURE hashtag is added AFTER this function runs,
 * so maxLen accounts for it already.
 */
export function fitToTwitterLimit(text: string, maxLen: number): string {
  if (text.length <= maxLen) return text;

  const lines = text.split("\n");
  const lastLine = lines[lines.length - 1].trim();
  const hasHashtags = lastLine.startsWith("#");

  let body = hasHashtags ? lines.slice(0, -1).join("\n").trimEnd() : text;
  let hashtags = hasHashtags
    ? lastLine.split(/\s+/).filter((t) => t.startsWith("#"))
    : [];

  // Drop topic hashtags one by one from the right
  while (hashtags.length > 0) {
    const candidate = `${body}\n\n${hashtags.join(" ")}`;
    if (candidate.length <= maxLen) return candidate;
    hashtags = hashtags.slice(0, -1);
  }

  // No hashtags left — trim body at last word boundary (no … — prompt bans it)
  if (body.length > maxLen) {
    const cut = body.substring(0, maxLen);
    const lastSpace = cut.lastIndexOf(" ");
    body = lastSpace > 0 ? cut.substring(0, lastSpace) : cut;
  }

  return body;
}

// ── Main function ─────────────────────────────────────────────────────────────

/**
 * Generates a Farsi tweet for today's post using Claude via the
 * Cloudflare AI Gateway (BYOK — Anthropic Provider Key injected automatically).
 */
export async function generateTweet(
  env: Env,
  input: TweetGenerationInput
): Promise<TweetGenerationResult> {
  const theme = TWEET_THEMES[input.themeIndex % TWEET_THEMES.length];
  const userPrompt = buildUserPrompt(input);

  // Cloudflare AI Gateway → Anthropic
  const endpoint = `https://gateway.ai.cloudflare.com/v1/${env.CLOUDFLARE_ACCOUNT_ID}/${env.CLOUDFLARE_GATEWAY_ID}/anthropic/v1/messages`;

  console.log(`[ai] Calling Claude — model: ${CLAUDE_MODEL}, theme: ${theme.key} (index ${input.themeIndex % TWEET_THEMES.length}), history: ${input.previousTweets.length} tweets`);

  const response = await fetch(endpoint, {
    method: "POST",
    headers: {
      "cf-aig-authorization": `Bearer ${env.CLOUDFLARE_API_TOKEN}`,
      "anthropic-version": "2023-06-01",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: CLAUDE_MODEL,
      max_tokens: 400,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: userPrompt }],
    }),
  });

  if (!response.ok) {
    const body = await response.text();
    console.error(`[ai] AI Gateway error ${response.status}: ${body}`);
    throw new Error(`Cloudflare AI Gateway error ${response.status}: ${body}`);
  }

  const data = await response.json<{
    content: Array<{ type: string; text: string }>;
    usage?: { input_tokens: number; output_tokens: number };
  }>();

  if (data.usage) {
    console.log(`[ai] Token usage — input: ${data.usage.input_tokens}, output: ${data.usage.output_tokens}`);
  }

  const rawText = data.content?.find((b) => b.type === "text")?.text?.trim();

  if (!rawText) {
    console.error(`[ai] Empty response from Claude: ${JSON.stringify(data)}`);
    throw new Error(
      `Claude returned an empty response. Full response: ${JSON.stringify(data)}`
    );
  }

  console.log(`[ai] Raw response: ${rawText.length} chars`);

  // Sanitise: strip wrapping quotes and any trailing ellipsis/suspension
  // Claude likes to end with "…" or "..." which makes tweets look like threads
  const cleaned = rawText
    .replace(/^["«]|["»]$/g, "")
    .replace(/[….،,\s]+$/, "")   // strip trailing … . ، , and whitespace
    .trim();

  // Twitter shortens ALL URLs to t.co (always 23 chars in their counter).
  // Budget: 279 - "\n\n".length(2) - URL_twitter_chars(23) - " #هوشنوشت".length(10) = 244
  const URL_TWITTER_CHARS = 23;
  const signatureSuffix = ` ${AI_SIGNATURE}`; // " #هوشنوشت" = 10 chars
  const maxBodyLen = 279 - 2 - URL_TWITTER_CHARS - signatureSuffix.length;

  // Fit the body + topic hashtags within the remaining budget
  const fitted = fitToTwitterLimit(cleaned, maxBodyLen);
  if (fitted.length < cleaned.length) {
    console.warn(`[ai] Tweet trimmed: ${cleaned.length} → ${fitted.length} chars`);
  }

  // Append the post URL and AI signature — always in code, never left to Claude
  const tweetText = `${fitted}\n\n${input.post.url}${signatureSuffix}`;

  console.log(`[ai] Final tweet: ${tweetText.length} chars`);

  return {
    text: tweetText,
    theme: theme.key,
    themeIndex: input.themeIndex % TWEET_THEMES.length,
  };
}
